### ISSUE TITLE
[CLI] Add support to specify directory / filename for output files

### ISSUE THREAD

**Issue by h3ssto** [SoftVarE-Group/d-dnnf-reasoner#31]
Currently, ddnnf saves the results of analyses such as commonality to the same directory as the input files, this is however not always feasible, especially when the input directory is mounted `readonly` in Docker/Podman. It would be great if the CLI would allow for the specification of an input directory. A solution via environment variables would be alright as well.

**Comment by uulm-janbaudisch** [comment]
> `./ddnnife file.dimacs -c ../test.csv` creates the file `../test.csv-features.csv`

This is already working and produces the output file in the given directory.

But I would still like to refactor the CLI to not construct paths but only take a output file as parameter or print to stdout.

**Comment by h3ssto** [comment]
Yes, this was not a suggestion, this is the state of the art, which is quite unintuitive imo. I would expect that in all these cases, the last argument of the lhs is treated as a path.
