### ISSUE TITLE
Data error！！

### ISSUE THREAD

**Issue by Reyotsed** [SoftVarE-Group/d-dnnf-reasoner#38]
In the first line of the file,small_example_c2d.nnf, in the example_input folder, the number of nodes should be 12, not 11. I debugged for half an hour because of this stupid error! I'm pissed off!

**Comment by Reyotsed** [comment]
Why did this stupid mistake go unnoticed for a year?

**Comment by Reyotsed** [comment]
I took a quick look in passing, and this part of the paper is also wrong

**Comment by SundermannC** [comment]
@Reyotsed Thanks a lot for the report. The header was indeed wrong and is now fixed. 
It appears like this went unnoticed as ddnnife just discards this number and instead uses the number of lines in the file.
